<html>

<head>
    <meta charset="utf-8">

    <!-- Importing Web Component's Polyfill -->
    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

    <script src="../../sinonjs/sinon.js"></script>

    <link rel="import" href="shared/helpers.html">

    <script src="../../web-component-tester/browser.js"></script>

    <!-- Step 1: import the element to test -->
    <link rel="import" href="../palindrom-error-catcher.html">
</head>

<body>
    <test-fixture id="text-fixture">
        <template>
            <palindrom-client></palindrom-client>
            <palindrom-error-catcher></palindrom-error-catcher>
        </template>
    </test-fixture>
    <script>
        describe('palindrom-error-catcher', function () {
            var textFixture, ppclient, palindromErrorCatcher, errorCatcherShadowRoot, originalConsoleError;
            before(function () {
                chai.use(palindromChaiPlugin);
                /* for some strange reason I couldn't find a trace for,
                when console.error is called, mocha assumes an exception happened,
                even if it is intended. This fixes the issue but doesn't affect the test scenario */
                originalConsoleError = console.error;
                console.error = function noop () {};
            });
            after(function() {
                // just to be clean
                console.error = originalConsoleError;
            })
            beforeEach(function () {
                textFixture = fixture('text-fixture');
                ppclient = textFixture[0];
                palindromErrorCatcher = textFixture[1];
                errorCatcherShadowRoot = palindromErrorCatcher.shadowRoot;
                
            });
            describe('Connection errors: UI', function () {
                it('Should show UI after connection error', function () {
                    const errorPane = errorCatcherShadowRoot.querySelector('.connection-error-pane');

                    expect(errorPane).to.be.not.visible;
                    ppclient.fireConnectionErrorEvent();
                    expect(errorPane).to.be.visible;
                });
                it('Should show UI after generic error', function () {
                    const errorPane = errorCatcherShadowRoot.querySelector('.generic-error-pane');

                    expect(errorPane).to.be.not.visible;
                    ppclient.fireGenericErrorEvent();
                    expect(errorPane).to.be.visible;
                });
            });
        });
    </script>

</body>

</html>